// const items = [
//   {
//     id: 1,
//     title: "Squid Game",
//     image:
//       "https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABVTynECAebarq147fY0p6EuxkYt8UYFoqAeebr4iy4g5RgUf0QyUDLTmGWUrL5NRMEjm7tg1F1fBfYwn2jAHoK3g87V0TC9ksP2FROWXDw.jpg?r=609",
//     genre: ["Action", "Adventure"],
//     duration: 180,
//     language: ["Enlish", "Hindi"],
//     certificate: "UA",
//     director: "",
//     rating: "8.5",
//     status: "coming from server",
//     // enum : ["upComing ", "Now Showing", "Completed"]
//   },
//   {
//     id: 2,
//     title: "Games of Thrones",
//     image: "https://images.static-bluray.com/products/20/6361_31_front.jpg",
//     genre: ["Action", "Adventure"],
//     duration: 180,
//     language: ["Enlish", "Hindi"],
//     certificate: "UA",
//     director: "",
//     rating: "8.5",
//     status: "coming from server",
//     // enum : ["upComing ", "Now Showing", "Completed"]
//   },
//   {
//     id: 3,
//     title: "Stranger Things",
//     image:
//       "https://upload.wikimedia.org/wikipedia/en/b/b1/Stranger_Things_season_1.jpg",
//     genre: ["Action", "Adventure"],
//     duration: 180,
//     language: ["Enlish", "Hindi"],
//     certificate: "UA",
//     director: "",
//     rating: "8.5",
//     status: "coming from server",
//     // enum : ["upComing ", "Now Showing", "Completed"]
//   },

//   {
//     id: 4,
//     title: "Fast & Furious",
//     image:
//       "https://upload.wikimedia.org/wikipedia/en/8/8f/Fast_and_Furious_Poster.jpg",
//     genre: ["Action", "Adventure"],
//     duration: 180,
//     language: ["Enlish", "Hindi"],
//     certificate: "UA",
//     director: "",
//     rating: "8.5",
//     status: "coming from server",
//     // enum : ["upComing ", "Now Showing", "Completed"]
//   },
// ];

// export default items;

const movie = [
  {
    id: 1,
    name: "The Dark Knight",
    image: "/Movies/m0.jpg",
    duration: "152 min",
    language: "English",
    genre: "Action, Crime, Drama",
    certificate: "UA",
    rating: 9.0,
    directed_by: "Christopher Nolan",
    released_date: "2008-07-18",
  },
  {
    id: 2,
    name: "Inception",
    image: "/Movies/m2.webp",
    duration: "148 min",
    language: "English",
    genre: "Action, Sci-Fi, Thriller",
    certificate: "UA",
    rating: 8.8,
    directed_by: "Christopher Nolan",
    released_date: "2010-07-16",
  },
  {
    id: 3,
    name: "Interstellar",
    image: "/Movies/m3.jpg",
    duration: "169 min",
    language: "English",
    genre: "Adventure, Drama, Sci-Fi",
    certificate: "U",
    rating: 8.7,
    directed_by: "Christopher Nolan",
    released_date: "2014-11-07",
  },
  {
    id: 4,
    name: "Parasite",
    image: "/Movies/m4.jpg",
    duration: "132 min",
    language: "Korean",
    genre: "Drama, Thriller",
    certificate: "A",
    rating: 8.5,
    directed_by: "Bong Joon Ho",
    released_date: "2019-05-30",
  },
  {
    id: 5,
    name: "Spirited Away",
    image: "/Movies/m5.jpg",
    duration: "125 min",
    language: "Japanese",
    genre: "Animation, Adventure, Fantasy",
    certificate: "U",
    rating: 8.6,
    directed_by: "Hayao Miyazaki",
    released_date: "2001-07-20",
  },
  {
    id: 6,
    name: "The Godfather",
    image: "/Movies/m6.jpg",
    duration: "175 min",
    language: "English",
    genre: "Crime, Drama",
    certificate: "A",
    rating: 9.2,
    directed_by: "Francis Ford Coppola",
    released_date: "1972-03-24",
  },
  {
    id: 7,
    name: "Pulp Fiction",
    image: "/Movies/m7.jpg",
    duration: "154 min",
    language: "English",
    genre: "Crime, Drama",
    certificate: "A",
    rating: 8.9,
    directed_by: "Quentin Tarantino",
    released_date: "1994-10-14",
  },
  {
    id: 8,
    name: "3 Idiots",
    image: "/Movies/m8.jpg",
    duration: "170 min",
    language: "Hindi",
    genre: "Comedy, Drama",
    certificate: "UA",
    rating: 8.4,
    directed_by: "Rajkumar Hirani",
    released_date: "2009-12-25",
  },
  {
    id: 9,
    name: "Dangal",
    image: "/Movies/m9.jpg",
    duration: "161 min",
    language: "Hindi",
    genre: "Action, Biography, Drama",
    certificate: "U",
    rating: 8.3,
    directed_by: "Nitesh Tiwari",
    released_date: "2016-12-23",
  },
  {
    id: 10,
    name: "Your Name",
    image: "/Movies/m10.jpg",
    duration: "106 min",
    language: "Japanese",
    genre: "Animation, Drama, Fantasy",
    certificate: "U",
    rating: 8.4,
    directed_by: "Makoto Shinkai",
    released_date: "2016-08-26",
  },
  {
    id: 11,
    name: "Gladiator",
    image: "/Movies/m11.jpg",
    duration: "155 min",
    language: "English",
    genre: "Action, Adventure, Drama",
    certificate: "UA",
    rating: 8.5,
    directed_by: "Ridley Scott",
    released_date: "2000-05-05",
  },
  {
    id: 12,
    name: "The Matrix",
    image: "/Movies/m12.jpg",
    duration: "136 min",
    language: "English",
    genre: "Action, Sci-Fi",
    certificate: "A",
    rating: 8.7,
    directed_by: "Lana Wachowski, Lilly Wachowski",
    released_date: "1999-03-31",
  },
  {
    movie_id: 13,
    name: "Whiplash",
    image: "/Movies/m13.jpg",
    duration: "106 min",
    language: "English",
    genre: "Drama, Music",
    certificate: "A",
    rating: 8.5,
    directed_by: "Damien Chazelle",
    released_date: "2014-10-10",
  },
  {
    id: 14,
    name: "Coco",
    image: "/Movies/m14.jpg",
    duration: "105 min",
    language: "English",
    genre: "Animation, Adventure, Family",
    certificate: "U",
    rating: 8.4,
    directed_by: "Lee Unkrich",
    released_date: "2017-11-22",
  },
  {
    id: 15,
    name: "Django Unchained",
    image: "/Movies/m15.jpg",
    duration: "165 min",
    language: "English",
    genre: "Drama, Western",
    certificate: "A",
    rating: 8.4,
    directed_by: "Quentin Tarantino",
    released_date: "2012-12-25",
  },
  {
    id: 16,
    name: "The Lion King",
    image: "/Movies/m16.webp",
    duration: "88 min",
    language: "English",
    genre: "Animation, Adventure, Drama",
    certificate: "U",
    rating: 8.5,
    directed_by: "Roger Allers, Rob Minkoff",
    released_date: "1994-06-24",
  },
  {
    id: 17,
    name: "Sholay",
    image: "/Movies/m17.jpg",
    duration: "204 min",
    language: "Hindi",
    genre: "Action, Adventure, Comedy",
    certificate: "U",
    rating: 8.1,
    directed_by: "Ramesh Sippy",
    released_date: "1975-08-15",
  },
  {
    id: 18,
    name: "The Truman Show",
    image: "/Movies/m18.webp",
    duration: "103 min",
    language: "English",
    genre: "Comedy, Drama",
    certificate: "U",
    rating: 8.2,
    directed_by: "Peter Weir",
    released_date: "1998-06-05",
  },
  {
    id: 19,
    name: "Amélie",
    image: "/Movies/m19.png",
    duration: "122 min",
    language: "French",
    genre: "Comedy, Romance",
    certificate: "UA",
    rating: 8.3,
    directed_by: "Jean-Pierre Jeunet",
    released_date: "2001-04-25",
  },
  {
    id: 20,
    name: "Spiderman: Into the Spider-Verse",
    image: "/Movies/m20.jpg",
    duration: "117 min",
    language: "English",
    genre: "Animation, Action, Adventure",
    certificate: "U",
    rating: 8.4,
    directed_by: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    released_date: "2018-12-14",
  },
];

export default movie;
