const snacks = [
  {
    id: 1,
    image: "/Snack/snack5.jpg",
    name: "Large Popcorn",
    category: "popcorn",
    price: "250",
    isAvailable: true,
  },
  {
    id: 2,
    image: "/Snack/snack21.avif",
    name: "Dual SandWich",
    category: "sandwich",
    price: "150",
    isAvailable: true,
  },
  {
    id: 3,
    image: "/Snack/snack24.jpg",
    name: "Large Burger",
    category: "burger",
    price: "180",
    isAvailable: true,
  },
  {
    id: 4,
    image: "/Snack/snack27.avif",
    name: "Full Coffee",
    category: "coffee",
    price: "250",
    isAvailable: true,
  },
  {
    id: 5,
    image: "/Snack/snack20.webp",
    name: "Full Pepsi",
    category: "pepsi",
    price: "140",
    isAvailable: true,
  },
  {
    id: 6,
    image: "/Snack/snack17.webp",
    name: "Large Mocktail",
    category: "mocktail",
    price: "190",
    isAvailable: true,
  },
  {
    id: 7,
    image: "/Snack/snack13.avif",
    name: "Full Cold Coffee",
    category: "coffee",
    price: "140",
    isAvailable: true,
  },
  {
    id: 8,
    image: "/Snack/snack2.png",
    name: "small Potato Chips",
    category: "chips",
    price: "110",
    isAvailable: true,
  },
  {
    id: 9,
    image: "/Snack/snack25.jpg",
    name: "Large Combo",
    category: "combo",
    price: "240",
    isAvailable: true,
  },
];

export default snacks;
